### ISSUE TITLE
Tests quite complex

### ISSUE THREAD

**Issue by des-des** [stevehopkinson/modules-challenge#1]
My main fear here is that students will spend all of their time trying to understand the test code, which although is valuable, will mean that many of the students will not spend time solving the problem.

This might seem like counter intuitive advise, given that we want as much testing as possible, but I think the students should use their browser to test. Once the students have learned tape and shot, they can test their servers in a less complex way.

We could then actually build out the exercise a bit, and give the students more to refactor..

Thoughts?

**Comment by jbesraa** [comment]
I think it can very useful for some of the students and complex for others. 
I'm in favor of keeping it and maybe explain it before the workshop starts.

**Comment by stevehopkinson** [comment]
I would say that many of the challenges we had during FAC9 had tests that weren't obvious - they were more there to make sure you hadn't broken the code, rather than anything else. I was tempted to include tests in Tape, but that added a whole layer of complexity that didn't feel appropriate. I'd be tempted to give it a go and see how people respond – otherwise we'll never know.

**Comment by jsms90** [comment]
@stevehopkinson 
> many of the challenges we had during FAC9 had tests that weren't obvious

not the best argument, given that FAC9 barely included tests in our projects at all... :laughing: 

But I'm all for keeping this in!

**Comment by des-des** [comment]
Coolio happy to close this
